name: Hub
version: ${project.version}
main: com.redblock6.hub.Main
api-version: 1.16
authors: [Redblock6]
description: Hub plugin for mc.redblock6.com
website: mc.redblock6.com
depend: [ProtocolLib]
softdepend: [HolographicDisplays, NBTAPI]
loadbefore: [Citizens]

commands:
  gamemenu:
    description: Opens the gamemenu
  gmc:
    description: Sets your gamemode to creative
  gms:
    description: Sets your gamemode to survival
  gma:
    description: Sets your gamemode to adventure
  gmsp:
    description: Sets your gamemode to spectator
  kitpvp:
    description: Opens the sub-menu for kitpvp
  pkrun:
    description: Opens the sub-menu for PKRUN
  deathrun:
    description: Opens the sub-menu for deathrun
  oitq:
    description: Opens the sub-menu for oitq
  tutorial:
    description: Sends the player into tutorial mode
  stop:
    description: Sends the player into tutorial mode

permissions:
  redblock.gamemode.creative:
    description: Sets your gamemode to creative
  redblock.gamemode.survival:
    description: Sets your gamemode to survival
  redblock.gamemode.adventure:
    description: Sets your gamemode to adventure
  redblock.gamemode.spectator:
    description: Sets your gamemode to spectator